services:
  - type: web
    name: novelnet
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_admin
    startCommand: gunicorn novelnet.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: netnovel.onrender.com
      - key: SECRET_KEY
        generateValue: true
      # Email settings for Gmail SMTP
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: infonovelnet@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: xerxwspajazaizrq
      - key: DEFAULT_FROM_EMAIL
        value: infonovelnet@gmail.com
