services:
  - type: web
    name: novelnet
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python create_admin.py
    startCommand: gunicorn novelnet.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: netnovel.onrender.com
      - key: SECRET_KEY
        generateValue: true
      # Email settings for Mailgun
      - key: EMAIL_HOST
        value: smtp.mailgun.org
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: postmaster@kapil@sandbox25ef15590d3648439fa7f5a303e41feb.mailgun.org
      - key: EMAIL_HOST_PASSWORD
        value: your-mailgun-smtp-password
      - key: DEFAULT_FROM_EMAIL
        value: postmaster@kapil@sandbox25ef15590d3648439fa7f5a303e41feb.mailgun.org
