# Generated by Django 5.0.8 on 2025-10-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_authors_alter_book_categories'),
    ]

    operations = [
    ]
