# Generated by Django 5.0.8 on 2025-10-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20251019_1434'),
    ]

    operations = [
    ]
