# Generated by Django 5.0.8 on 2025-10-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
